### ISSUE TITLE
P2 : Add Participant : Suggestion : Which fields are mandatory and which are not is not shown properly. It can be shown using the '*' at beginning of the field.

### ISSUE THREAD

**Issue by rohitb123** [parth-gudhka/MHT_Portal#48]

**Comment by 0xelectron** [comment]
Completed! Currently the mandatory fields will appear red. I will add more changes afterwards. For now, this will do!

**Comment by sagarpomal** [comment]
Thanks for this, later we can put (*) or something else. For now this will do.
