### ISSUE TITLE
P1: Reports: Coordinator Reports : Listing page : Sub Role not displayed,Excel: Role not displayed

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#62]
Scenario: To verify admin is able to view the same data as displayed in the report and the excel

Steps:
1.Login as admin
2.Navigate to the Co-ordinator Details Report
3.Generate data for a center
4.View the co-ordinator details listing page
5.Download excel for the center

Actual Result: 
In listing page,Role data is displayed
In downloaded excel, Sub Role data is displayed

Expected Result:
In Listing page, Sub Role data should be displayed
In downloaded excel, Role data should be displayed

**Comment by dhrumil24patel** [comment]
Role and Sub Role added in Excel and List view respectively.

**Comment by dhrumil24patel** [comment]
@milesh81 Please test the modified report.
