### ISSUE TITLE
P1: YMHT attendance report displayed error page when report is generated with only start date

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#66]
![test data1](https://cloud.githubusercontent.com/assets/14317287/10563341/1f478ed2-75a4-11e5-8ca9-c78a3e6abbd2.png)

![error message](https://cloud.githubusercontent.com/assets/14317287/10563349/cc9e0d4a-75a4-11e5-99c3-375fd55f62bf.png)

http://127.0.0.1:8000/reports/ymht_attendance/?center=3&start=2015-10-18&end=&Generate-btn=Generate%21

Scenario: To verify admin is able to generate YMHT attendance report

Steps:
1.Login as admin
2.Navigate to Reports: Attendance Reports : YMHT Attendance Details
3.Generate data for a center with only start date as per the attachment.

Actual Result: Error page is displayed.refer attachment.

Expected Result: Proper validation message should be displayed

**Comment by dhrumil24patel** [comment]
Above mentioned error was showing because the field name was changed to 'report' from 'session' so the system couldn't find the report_id column inside database.
