### ISSUE TITLE
P1: YMHT attendance report displayed error page when report is generated with valid start date and end date

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#67]
![test data 2](https://cloud.githubusercontent.com/assets/14317287/10563389/e67a0150-75a5-11e5-9e2a-7d1eb900aae8.png)
![error page](https://cloud.githubusercontent.com/assets/14317287/10563388/e670dcf6-75a5-11e5-9a00-a38538b7e5fd.png)

Scenario: To verify admin is able to generate YMHT attendance report with valid start date and end date

Steps:
1.Login as admin
2.Navigate to Reports: Attendance Reports : YMHT Attendance Details
3.Generate data for a center with valid start date and end date

Actual Result: Error page is displayed
http://127.0.0.1:8000/reports/ymht_attendance/?center=3&start=2015-10-18&end=2015-12-18&Generate-btn=Generate%21

Expected Result: Report should be generated

**Comment by dhrumil24patel** [comment]
Error was shown because of the same reason as previously closed issue.
