### ISSUE TITLE
P1: Error page is displayed when admin downloads YMHT attendance excel file.Refer attachments.

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#68]
![testdata3](https://cloud.githubusercontent.com/assets/14317287/10563436/adafb43a-75a7-11e5-85af-180a6ddea08a.png)

![excel file error page](https://cloud.githubusercontent.com/assets/14317287/10563437/af726fc4-75a7-11e5-9c9d-437a3a617426.png)

Scenario: To verify admin is able to download the YMHT attendance excel file

Steps:
1.Login as admin
2.Navigate to Reports: Attendance Reports : YMHT Attendance Details
3.Fill valid start date and end date for a center
4.Click on "Download as Excel" button

Actual Result: Error page is displayed
http://127.0.0.1:8000/reports/ymht_attendance/?center=3&start=2015-01-18&end=2015-12-18&Download-btn=Download+as+Excel+%21

Expected Result: Data should be generated

**Comment by sagarpomal** [comment]
@dhrumil24patel - Please have a look.
