### ISSUE TITLE
P1: Attendance Reports : YMHT Attendance Details: "Attendance" header and % symbol are not displayed properly.Refer attachments.

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#69]
[YMHT Attendance Details.xlsx](https://github.com/parth-gudhka/MHT_Portal/files/15571/YMHT.Attendance.Details.xlsx)
![test data4](https://cloud.githubusercontent.com/assets/14317287/10563640/62105000-75ae-11e5-96c9-4665f38d6ada.png)

Steps:
1.Login as admin
2.Navigate to Reports: Attendance Reports : YMHT Attendance Details
3.Fill valid start date and end date for a center
4.Click on "Generate" button
5.In the listing page,attendance is displayed in % format.
6.Download the excel file
7.View the Attendance column

Actual Result: Only numeric value is displayed in the Attendance column in the downloaded excel file.

Expected Result: Change the Column name "Attendance" to "Attendance Percentage" in the listing page.
In the excel file,Change the Column name "Attendance" to "Attendance Percentage" and add the percentage symbol next to the numeric value of the record.

**Comment by dhrumil24patel** [comment]
Done
