### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ghost** [parth-gudhka/MHT_Portal#7]
Add Department field into "Global Event Sewa" Header
Remove/Hide "Sewa Name" field from "Local Event Sewa Details"
Rename "Project Responsible" field to "Coordinator Name" from GNC Sewa Details header.

**Comment by parth-gudhka** [comment]
@gaurav08suri @sagarpomal @sidharthshah @shyamhd Any idea what this ghost is and how it created an issue?
