### ISSUE TITLE
P1: Reports: Attendance Reports: Sr.No. column is not displayed in the listing page and excel file.

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#70]
Scenario: To verify Sr.No. column is displayed in the listing page and downloaded excel file

Steps:
1.Login as admin
2.Navigate to Reports: Attendance Reports : YMHT Attendance Details
3.Fill valid start date and end date for a center
4.Click on "Generate" button
5.View the listing page
6.Download the excel file
7.View the excel file
8.Navigate to Reports: Attendance Reports : YMHT Details
9.Select a center
10.Click on "Generate" button
11.View the listing page
12.Download the excel file
13.View the excel file

Actual Result:
Sr.No. column is not displayed in:
YMHT Attendance listing page
YMHT Attendance downloaded excel file
YMHT Details listing page
YMHT Details downloaded excel file

Expected Result:
Sr.No. column should be  displayed in:
YMHT Attendance listing page
YMHT Attendance downloaded excel file
YMHT Details listing page
YMHT Details downloaded excel file

**Comment by dhrumil24patel** [comment]
Done
