### ISSUE TITLE
P1: Session attendance report is not generated.Refer attachments.

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#71]
![test data 5](https://cloud.githubusercontent.com/assets/14317287/10563717/e43de3d6-75b2-11e5-836f-0b9910807767.png)

![listing error page](https://cloud.githubusercontent.com/assets/14317287/10563718/e78f506a-75b2-11e5-8047-0ce5454bac55.png)

Scenario:
To verify session attendance report is generated

Steps:
1.Login as admin
2.Navigate to Reports: Session Reports : Session Attendance
3.Fill valid start date and end date for a center
4.Click on "Generate" button

Actual Result: Error page is displayed
http://127.0.0.1:8000/reports/attendance/?center=1&start=2013-01-01&end=2015-10-18&Generate-btn=Generate%21

Expected Result: Report should be generated

**Comment by gaurav08suri** [comment]
Fixed.
