### ISSUE TITLE
P1: Reports: Session Reports: Sr.No. column is not displayed in the listing page and excel file.

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#73]
Scenario: 
To verify Sr.No. column is displayed in the listing page and downloaded excel file

Steps:
1.Login as admin
2.Navigate to Reports: Session Reports : Session Attendance
3.Fill valid start date and end date for a center
4.Click on "Generate" button
5.View the listing page
6.Download the excel file
7.View the excel file

Actual Result:
Sr.No. column is not displayed in:
Session Attendance listing page
Session Attendance downloaded excel file

Expected Result:
Sr.No. column should be  displayed in:
Session Attendance listing page
Session Attendance downloaded excel file

**Comment by dhrumil24patel** [comment]
Done
