### ISSUE TITLE
P1: Error page is displayed when session report excel file is downloaded.Refer attachments.

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#74]
![test data 6](https://cloud.githubusercontent.com/assets/14317287/10563756/afbcad16-75b4-11e5-8212-abdd69afad6a.png)
![download excel file error page](https://cloud.githubusercontent.com/assets/14317287/10563757/b0564df4-75b4-11e5-9ad4-c326dd53ba8a.png)

Scenario:
To verify admin is able to download the session attendance excel file

Steps:
1.Login as admin
2.Navigate to Reports: Session Reports : Session Attendance
3.Fill valid start date and end date for a center
4.Click on "Download as Excel" button

Actual Result: Error page is displayed

http://127.0.0.1:8000/reports/attendance/?center=1&start=2013-01-01&end=2015-11-01&Download-btn=Download+as+Excel%21

Expected Result: Excel file should downloa

**Comment by gaurav08suri** [comment]
Fixed.
