### ISSUE TITLE
P1:Frontend:LoggedIn user name is not displayed at the home page,as it is displayed in the backend.Refer attachments.

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#80]
http://127.0.0.1:8000/home/
![backend](https://cloud.githubusercontent.com/assets/14317287/10715468/bdb116d0-7b3d-11e5-9d0b-8553c74fb627.png)

![frontend](https://cloud.githubusercontent.com/assets/14317287/10715470/ce48deb0-7b3d-11e5-8f43-54c91bb6f5ff.png)

**Comment by sagarpomal** [comment]
@milesh81- Fixed. Please have a look at this and all other fixed issues.
