### ISSUE TITLE
P1:For "Staff status" user , Add session page is not displayed.Refer attachment.

### ISSUE THREAD

**Issue by milesh81** [parth-gudhka/MHT_Portal#83]
![403 forbidden](https://cloud.githubusercontent.com/assets/14317287/10715731/7b9664ae-7b46-11e5-939f-433e7aa47911.png)

**Comment by gaurav08suri** [comment]
@milesh81 - Fixed. Please check with the updated code.

**Comment by sagarpomal** [comment]
Resolved
